export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*//')"
export TERMINAL="termite"
export ZDOTDIR="$HOME/.config/zsh"
export EDITOR="nvim"
export FILE="$HOME/.config/vifm/scripts/vifmrun"
export BROWSER="brave"
export READER="zathura"
export INTERFACE=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $5')
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx
