#!/bin/sh
xrandr --dpi 96
xset r rate 300 50 &
setxkbmap dk &
nitrogen --set-zoom-fill --random ~/Pictures/Wallpapers &
(sleep 2s; sudo pacman -Syy) &

autostart="mpd xcompmgr dunst unclutter pipewire"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
