#!/bin/sh

setxkbmap dk &
unclutter &
xset r rate 300 50 &
xcompmgr &
dunst &
nitrogen --set-zoom-fill --random ~/Pictures/Wallpapers &
(sleep 2s; sudo pacman -Syy) &

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
