#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
        ffmpeg="ffmpeg -hide_banner" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
        ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
        ccat="highlight --out-format=ansi" \
	ka="killall" \
	YT="youtube-viewer" \
	sdn="sudo poweroff" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	br="br -h"


