#!/usr/bin/env sh
weather=$(curl -Ss "https://wttr.in?0&T&Q" | cut -c 16- | head -2 | xargs echo)
[[ $weather == *Partly* ]] && echo " $weather"
[[ $weather == *Cloudy* ]] && echo " $weather"
[[ $weather == *Overcast* ]] && echo " $weather"
[[ $weather == *"Light rain"* ]] && echo " $weather"
[[ $weather == *"Light drizzle"* ]] && echo "殺$weather"
[[ $weather == *Patchy* ]] && echo " $weather"
[[ $weather == *sleet* ]] && echo "ﭽ $weather"
